name: CI-Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    - name: Checkout
      uses: actions/checkout@v4

    - name: CI
      uses: ./
      with:
        ignore: dist
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
        codecov-go-race: false
        publish-asset: ci-action.exe
        main-branch: master
      env:
        GOOS: windows
        GOARCH: 386
