name: CI - golang
on:
  workflow_call:
    inputs:
      commit_name:
        required: true
        type: string
    secrets:
      reporeading_token:
        required: true
      personal_token:	
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Rebuild airs-bp3
      run: |
        git config --global url."https://${{ secrets.reporeading_token }}:x-oauth-basic@github.com".insteadOf "https://github.com"
        curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/rebuild-test-bp3.sh | bash
      env: 
        github_token: ${{ secrets.reporeading_token }}
        gh_event: ${{ github.event_name }}

    - name: Push changes to pb3
      if: success()	      
      uses: actions-js/push@master
      with:
        directory: ../../${{ github.event.repository.name }}/airs-bp3
        repository: untillpro/airs-bp3
        message: "voedger: ${{ inputs.commit_name }}"
        branch: "main"
        github_token: ${{ secrets.personal_token }}
