name: CI - golang
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
      test_folder:
        required: false
        type: string
    secrets:
      reporeading_token:
        required: true
      codecov_token:
        required: true
      chargebee_token:
        required: true
      chargebee_sitename:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        cache: false

    # Install TinyGo 
    - name: Install TinyGo
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v0.32.0/tinygo_0.32.0_amd64.deb
        sudo dpkg -i tinygo_0.34.0_amd64.deb

    - name: Checkout
      uses: actions/checkout@v4

    - name: Check pull request file size
      if: github.event_name == 'pull_request'
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/checkPR.sh | bash 
      env: 
        token: ${{ secrets.reporeading_token }}
        pr_number: ${{ github.event.number }}

    - name: Cache Go - Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        organization: 'untillpro,heeus'
        token: ${{ secrets.reporeading_token }}
        codecov-token: ${{ secrets.codecov_token }}
        run-mod-tidy: false
        codecov-go-race: false
      env:
        CHARGEBEE_PUBLISHABLE_KEY: ${{ secrets.chargebee_token }}
        CHARGEBEE_SITE_NAME: ${{ secrets.chargebee_sitename }}
        HEEUS_SKIP_SLOW_TESTS: 0

    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"

    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"
