name: CI - golang
on:
  workflow_call:
    inputs:
      ignore_copyright:
        required: false
        type: string
      test_folder:
        required: false
        type: string
      ignore_bp3:
        required: false
        type: string
      short_test:
        required: false
        type: string
    secrets:
      reporeading_token:
        required: true
      codecov_token:
        required: true
      personal_token:	
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0      

    - name: Check pull request file size
      if: github.event_name == 'pull_request'
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/checkPR.sh | bash 
      env: 
        token: ${{ secrets.reporeading_token }}
        pr_number: ${{ github.event.number }}

    - name: Cache Go - Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: CI
      uses: untillpro/ci-action@master
      with:
        ignore: ${{ inputs.ignore_copyright }}
        test-folder: ${{ inputs.test_folder }}
        organization: 'untillpro,heeus'
        token: ${{ secrets.reporeading_token }}
        codecov-token: ${{ secrets.codecov_token }}
        short-test: ${{ inputs.short_test == 'true' }}
        run-mod-tidy: false

    - name: Check copyright
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/check_copyright.sh | bash -s "$(go env GOPATH)"

    - name: Linters
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/gbash.sh | bash -s "$(go env GOPATH)"
      env: 
        testfolder: ${{ inputs.test_folder }}

    - name: Rebuild airs-bp3
      if: ${{ (contains(github.repositoryUrl, 'voedger' ) || contains(github.repositoryUrl, 'untillpro' )) && (inputs.ignore_bp3 != 'true') &&
        (github.event_name == 'push') && (github.ref != 'refs/heads/rc' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/rcfix') }}
      run: curl -s https://raw.githubusercontent.com/untillpro/ci-action/master/scripts/rebuild-test-bp3.sh | bash
      env: 
        github_token: ${{ secrets.reporeading_token }}
        gh_event: ${{ github.event_name }}

